# Generated by Django 5.0.6 on 2024-06-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
